version: '3.9'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./app/:/app/
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose: 
      - 5432:5432

volumes:
  postgres_data:
